### ISSUE TITLE
Efficiently Clearing the Buffer via Consumer

### ISSUE THREAD

**Issue by RobDavenport** [mgeier/rtrb#92]
Hi thanks for the crate!

I'm looking for advice on what the best way to just drop all of the data in the buffer from the consumers side.

Currently I'm just doing a `while let` loop on `pop()` and ignoring the result. Is there a better way to do this? Say in the case where we only want to consume the first 10 elements, drop the rest, and then consume 10 more later?

**Comment by mgeier** [comment]
> Currently I'm just doing a `while let` loop on `pop()` and ignoring the result.

I think that's perfectly fine.

Theoretically, each `pop()` call might access some atomic variables, but they are cached, so I think it doesn't really matter in this situation.

However, if you want a different way, you can try this (given a consumer `c`):

```rust
c.read_chunk(c.slots()).unwrap().commit_all();
```

But note that this might also have a slightly different behavior, because the number of available slots is only checked once in the beginning.

**Comment by RobDavenport** [comment]
That is a great suggestion which makes a lot of sense with the current API. I'll close the issue - thanks!
